### ISSUE TITLE
Tap outside to close

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [react-native-community/react-native-modal#11]
Is there a way to implement that function? Right now when I tap on the darkened region, the modal doesn't close.

**Comment by mmazzarolo** [comment]
Hey!  
It should be possible by toying a bit with the touchable options of [this View](https://github.com/mmazzarolo/react-native-animated-modal/blob/master/src/index.js#L107).  
Would you mind giving it a try and submitting a PR?  
Otherwise I'll take a look at it in my spare time :)

**Comment by DavidKongDesheng** [comment]
😆 pls add this function~~ thanks

**Comment by Doko-Demo-Doa** [comment]
Thank you @mmazzarolo , actually I fixed using exactly same method you mentioned. It works, but since the first image in your preview images (on README.md) does it correctly, I thought it was implemented already, wasn't it?

**Comment by DavidKongDesheng** [comment]
@Doko-Demo-Doa according to the source code, haven't implemented yet, there is no close event on backdrop view or you can do sth like this, not so good but should be work.

```
<TouchableWithoutFeedback onPress={() => this.setState({ visible: false })}>
        <Modal isVisible={this.state.visible}  ...>
            <TouchableWithoutFeedback onPress={() => {}}>
                    ... your custom view
            </TouchableWithoutFeedback
       </Modal>
</TouchableWithoutFeedback>
```

**Comment by mmazzarolo** [comment]
@Doko-Demo-Doa oh wow, honestly I don't remember how I implemented it for that screenshot (I did it in a customized version of this lib 😞 ).  

@DavidKongDesheng the problem with that solution is that clicking everywhere on the modal will close it. 
In my opinion the right solution would be using `onStartShouldSetResponderCapture` (or [something similar](https://facebook.github.io/react-native/docs/view.html) in the right place.  
The perfect solution would be that:  
- The backdrop should respond to the user touch (end by default trigger `onClose` or `onBackdropPress`);
- The view content should not respond to the backdrop touch, of course;
- The view content can have another independent button/touchable component inside.  

What do you think guys?  

Also, thank you @Doko-Demo-Doa and @DavidKongDesheng for the discussion, any feedback is of course warmly welcomed! 😸

**Comment by mmazzarolo** [comment]
I played a bit.  
It seems that the right way to handle it is by applying something like this: `
```javascript
onStartShouldSetResponder={() => {
  console.log('You pressed the backdrop!');
  return true;
}}
```
in the backdrop view. 
The problem with this approach is that it won't work correctly if you're centering the modal content using this:
```javascript
content: {
    flex: 1,
    justifyContent: 'center'
  }
```
...which is the default style applied to the content.  

I guess we should wait until react-native 0.43 stable lands and try changing that style to the new `margin: auto`, which I hope will make the backdrop press work correctly.  

I'm obviously open to discussions on the matter :)

**Comment by DavidKongDesheng** [comment]
@mmazzarolo On my solution I added two touch events, one for Modal itself which will close the modal, the other one is on the Modal content view which will do nothing 😸,  so only when you click the backdrop will close the modal.
<TouchableWithoutFeedback **_onPress={() => this.setState({ visible: false })}_**>
        <Modal isVisible={this.state.visible}  ...>
            <TouchableWithoutFeedback _**onPress={() => {}}>**_
                    ... your custom view
            </TouchableWithoutFeedback
       </Modal>
</TouchableWithoutFeedback>


Yup, the right solution should be make the backdrop respond to user touch.

**Comment by mmazzarolo** [comment]
Oh, nice! @DavidKongDesheng did you test your solution? 
Do you think it works correctly in most cases? 
Would you mind pasting here your complete snippet? 
Thanks!

**Comment by DavidKongDesheng** [comment]
@mmazzarolo Just added touch event to your example code, you can download and try,  but this is not the best way to implement.
[app.js.zip](https://github.com/mmazzarolo/react-native-animated-modal/files/881428/app.js.zip)

**Comment by Doko-Demo-Doa** [comment]
It seems that RN's modal component is pretty meh. If there's something like Dialog on Android or UIAlertView on iOS, it would be much better in this case :(

**Comment by warka0** [comment]
Hi,

I did exactly the same thing as @DavidKongDesheng but still don't working on my side !

```javascript
<TouchableWithoutFeedback onPress={() => this.setState({ modalVisible: false })}>
  <Modal transparent={true} ref="modal" visible={this.state.modalVisible} onRequestClose={this.close.bind(this)} animationType={this.state.animationType}>
    {this.renderOptionList()}
  </Modal>
</TouchableWithoutFeedback>
```

Or maybe i don't make it well... no ?

**Comment by emaLorenzo** [comment]
Hi! For me the solution of @DavidKongDesheng works great 🔥 
This is my code:

`constructor(props) {
    super(props);
    this.state = {
      isModalVisible: false
    }
  }

  _showModal() {
    this.setState({ isModalVisible: true })
  }

  _hideModal() {
    this.setState({ isModalVisible: false })
  }

  render() {
    const { alerts, showAlert } = this.props;
    return (
      <Container style={styles.container}>
        
        <TouchableWithoutFeedback onPress={() => this._hideModal() }>
          <Modal style={{margin: 0}} isVisible={this.state.isModalVisible}>
            <AccountModal />
          </Modal>
        </TouchableWithoutFeedback>

        ....`

Hope to be helpfull!

**Comment by warka0** [comment]
@emaLorenzo Thanks! But it doesn't work :( 

I don't know why it doesn't triggered the background :/

**Comment by DavidKongDesheng** [comment]
@warka0 Can't reproduce it according the attached codes, but it looks like you are using Modal from 'react-native' not from 'react-native-modal'

Or maybe try  
1. Remove onRequestClose, use onBackButtonPress instead
2. Set transparent={false}  and set 'red' as background color of your option list view, and check if really click on the background or somewhere else.
3. Check your renderOptionList().

Or more codes attach...

**Comment by jm90m** [comment]
@emaLorenzo Thanks for your solution, this worked for me 👏  👍

**Comment by kdenz** [comment]
@DavidKongDesheng Your solution worked for me, thanks! I hope this functionality is added soon to react-native-modal, it's such an important function.

**Comment by warka0** [comment]
I'll test it in two days. Cannot do it right now, i'm between two airports. :p

**Comment by mmazzarolo** [comment]
Hey, I'll try to take a look at it soon (PRs are obviously warmly welcome) :)
I still haven't tried the touchable wrapper but... doesn't it swallow the click buttons inside the modal (if any)? 🤔

**Comment by warka0** [comment]
Ok, i've tried and it's working, thanks!

**Comment by mmazzarolo** [comment]
@warka0, does it also work if you add a button inside the modal? Doesn't the `TouchableWithoutFeedback` wrapper on the modal swallow any touch to components inside it?

**Comment by jm90m** [comment]
@mmazzarolo So the modal is wrapped in `TouchableWithoutFeedback` but inside the modal I have a bunch of buttons wrapped around in `TouchableOpacity` and it works perfectly 👍

**Comment by mmazzarolo** [comment]
It was easier than I thought then :) Anyone willing to submit a PR?

**Comment by jm90m** [comment]
Sure I'll submit an example

**Comment by mmazzarolo** [comment]
@jm90m thank you for the PRs!
However...
Guys, with @emaLorenzo 's solution the modal is closed wherever you tap, while the issue was focused on closing the modal only when clicking on the backdrop 😿

**Comment by jm90m** [comment]
@mmazzarolo ohh, yeah looks like the main issue is more complex than it seems. I see, if I ever come across a solution, I'll submit a PR if no one has done so yet.

**Comment by zhantx** [comment]
You guys can take a look at my (repo)[https://github.com/zhantx/react-native-flex-modal], the idea is surround modal with 4 touchables. My initial solution was use a screen size touchable to perform tapToClose, a modal size touchable wrapping the modal to prevent the tap event gose up(no onpress). But then I found I can't use scrollview inside the touchable. So I came with up the solution in my repo

**Comment by zhantx** [comment]
And also, by adjusting the flex value of the four touchables, we can change the position of the modal, which also solve #22 , I already used my modal to create a popover

**Comment by mmazzarolo** [comment]
Hey @zhantx , thank you for contributing to the discussion 👍  
Glad there's someone else out there working with the modals.  
It seems you're solution is super-flexible, at the cost of being a bit more harder to grasp to someone new to RN.  
For this repo I'd like to keep the things as simple as possible, but your solution might be a good source of info for future implementations.  
Also, I only took a quick look at your code, can the modal be showed without setting all the dimensions (for example: can it adapt itself to a flex content)?
P.S.: PRs ans support are super welcome here if you're interested :)

**Comment by zhantx** [comment]
Hey @mmazzarolo , yeah I've been trying hard to simplify my modal by setting default props. so if none props are set then it will be at the center of the screen.
For you modal, to be honest adding tapToClose is impossible cuz your modal is controlled by prop `isVisible`, so the modal can't close itself directly. What I suggest is implement four touchables in your modal, and trigger an `onTapBackdrop` callback to let parent component to change the `isVisible`

**Comment by mmazzarolo** [comment]
Hey @zhantx, thanks!  

> so if none props are set then it will be at the center of the screen.  

Does it also resize itself based on the content size? 🤔 

> For you modal, to be honest adding tapToClose is impossible cuz your modal is controlled only by prop isVisible, so the modal can't close itself directly  

I'm not aiming at making the modal close itself directly, just to exposing an `onBackdropPress` listener, which can be used to close it from the modal's parent.  

>  (that's the reason why I choose ref methods open() and close())  

I'm trying to keep `react-native-modal` component as controlled as possible by staying away from refs method (at least until they're really needed).

**Comment by zhantx** [comment]
@mmazzarolo , check this out
[![Simulator Screen Shot 29 Apr 2017, 7.26.11 pm.png](https://s10.postimg.org/edcx0rnux/Simulator_Screen_Shot_29_Apr_2017_7.26.11_pm.png)](https://postimg.org/image/91y0g21s5/)

**Comment by mmazzarolo** [comment]
@zhantx this is super-cool, thanks!  
I'll take a look at a way to implement a similar solution here as soon as I have some free time.  
Obviously, backward-compatible PRs are welcome too.

**Comment by zhantx** [comment]
@mmazzarolo you are welcome mate, glad to be helpful.
my modal is just a side product of my work, may don't have time to contribute yours
anyway, best wishes to remaining works, cheers

**Comment by mlukasch** [comment]
Dont understand the Modal is taking the full screen for the backdrop overlay. So the solution doesnt work to wrap it inside a Touchable

**Comment by jm90m** [comment]
@zhantx  very helpful thx. For my case, I only had to use 2 `TouchableWithoutFeedback` (One for wrapping around the entire Modal and another for wrapping around the modal content):

<img width="662" alt="screen shot 2017-05-13 at 11 18 07 am" src="https://cloud.githubusercontent.com/assets/5067716/26026699/466e66b4-37ce-11e7-936c-3e79c6c99a66.png">

**Comment by zhantx** [comment]
as long as you don't have scrollview within modal:)

**Comment by jm90m** [comment]
@zhantx nope its a simple menu, but good point :)

**Comment by hellomaya** [comment]
This worked for me, edit the ```index.js``` to add a ```PanResponder```:

```
componentWillMount() {

    ......

        // for the backdrop touch to close
        this._panResponder = PanResponder.create({
            // Ask to be the responder:
            onStartShouldSetPanResponder: (evt, gestureState) => true,
            onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
            onMoveShouldSetPanResponder: (evt, gestureState) => true,
            onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,

            onPanResponderGrant: (evt, gestureState) => {
            },
            onPanResponderMove: (evt, gestureState) => {
            },
            onPanResponderTerminationRequest: (evt, gestureState) => true,
            onPanResponderRelease: (evt, gestureState) => {
                
                // close the modal
                this._close();
            },
            onPanResponderTerminate: (evt, gestureState) => {
            },
            onShouldBlockNativeResponder: (evt, gestureState) => {
                return true;
            },
        });
}

render() {
        ........
        <View
                    {...this._panResponder.panHandlers}
                    onLayout={this._handleLayout}
                    ref={ref => (this.backdropRef = ref)}
                    style={[
                        styles.backdrop,
                        {backgroundColor: backdropColor, width: deviceWidth, height: deviceHeight},
                    ]}
                />
        ........
}

```

**Comment by mmazzarolo** [comment]
Hey @hellomaya , thank you for sharing your snippet.  
How does it handle buttons inside the modal? Doesn't the panresponder swallow the press on them?

**Comment by jkomyno** [comment]
@hellomaya's solution seems to work only if we click the backdrop shadow placed at the horizontal margins. For instance, if I click above or below the Modal, `onPanResponderRelease` doesn't get triggered (I'm testing it with the official example on Android)

**Comment by hellomaya** [comment]
Hi, @mmazzarolo thanks for your asking and @jkomyno thanks for your test.

Sorry I have been busy working on something, my test initially is in my own project, and it's working well in both iOS simulator and Android device, I didn't see the issue you guys mentioned.

But to avoid the panresponder swallow issue, you will have to put all buttons in a separate component, like this:

```jsx
<Modal ....>
   <Content />
</Modal>

....
class Content extends Component {

    ......
    return (<View><Button onPress=.....></Button></View>)
```

**Comment by mmazzarolo** [comment]
> In the official example, it do have an issue like @jkomyno mentioned, the issue is because the default content style had flex: 1, so there is no room for backdrop, check index.style.js file. 
  
That's right, but using `flex: 1` is the only way to have the modal size resize itself based on its content (obviously, I'll be glad to be proven wrong).

**Comment by hellomaya** [comment]
Yes, it doesn't matter indeed, try add some margin around the ```content``` view, still be able to close the modal by tap outside. ```marginVertical: 25``` for example, larger than 20 was recommended to avoid invalid tap at top in iOS.

```jsx
<Modal style={marginVertical: 25...>
```

**Comment by tdimnet** [comment]
Hi there, I've just found some great solution (I do not know if someone has already found it).
I add two touchable and text elements within my component and I link to them my onPress event (and its relative closing modal window method).

Here is at my screen looks like: 
- the blue borders can hide the modal on Press;
- the select button takes the selected day (or period), save it into a state and close the modal window.
<img width="408" alt="capture d ecran 2017-07-17 a 17 55 04" src="https://user-images.githubusercontent.com/9935925/28277151-4ab48964-6b19-11e7-9e77-a760d7736066.png">

Below is the snippet of my code:
```
        <Modal
          isVisible={this.props.isVisible}
          backdropOpacity={.9} backdropColor={'#2B333D'} animationIn={'slideInDown'} animationOut={'slideOutUp'}
          style={Styles.modalContainer}
        >
            <TouchableWithoutFeedback
              onPress={() => this.props.hideModal()}
            >
              <Text style={{ backgroundColor: 'blue', height: 100, width: 350 }}> </Text>
            </TouchableWithoutFeedback>
          <View
            style={Styles.viewContainer}
          >
            {this.showPicker(this.props.metricFormat)}
            {this.showWeekSelection()}
            <TouchableOpacity
              onPress={() => {
                this.props.hideModal();
                this.props.onSelectDay(this.state.selectedStartDate, this.state.selectedEndDate);
              }}
              style={Styles.buttonContainer}
            >
              <Text
                style={Styles.text}
              >
                {I18n.t('select')}
              </Text>
            </TouchableOpacity>
          </View>
            <TouchableWithoutFeedback onPress={() => this.props.hideModal()} >
              <Text style={{ backgroundColor: 'blue', height: 100, width: 350 }}> </Text>
            </TouchableWithoutFeedback>
        </Modal>
```

**Comment by mmazzarolo** [comment]
Hey @tdimnet, thank you for contributing.  
The pattern you're following mimics the one showed by @zhantx (he uses 4 touchables in his solution).   
I'm stil not 100% sure on adding a similar solution to `react-native-modal` though, because I'm worried it might be a bit to complex to tweak later on (and might be a bit hard to configure for the users without adding a ton of props).  

What do you think?

**Comment by tdimnet** [comment]
Well, this is a really though question :).

I have been through this problem during this afternoon and I think this is maybe the most graceful solution for now. It lets you hide or show the modal window as you would need.

However I think you're right: adding this to your package could make the project more complex to custom and harder to understand and it really depends on the situation you are dealing with.

On my case I was looking for several ways to close the modal window:
- the first one by selecting a data within my calendar picker.
- the second one by simply close the window by tapping outside of it.

That being said I think we could simply update the readme file in order to other people have a better understanding and a good grasp of how to solve this common problem. 

If you want, I can open a PR this week which updates the readme file and presents this solution.

**Comment by mmazzarolo** [comment]
Thank you for your quick reply, I would be grateful for a PR on the README :)
Thanks!

**Comment by hash9** [comment]
There is an easy solution for closing the modal in react native for IOS: Define a TouchableOpacity inside the Modal.
`             <Modal animationType={"slide"}
                   transparent={true}
                   visible={this.state.visibleModal}>
                   <TouchableOpacity onPress = {() => {this.setState({visibleModal: false})} }>

                      <View style={styles.modalContent}>
                          <Row />
                      </View>

                  </TouchableOpacity>

            </Modal>`

**Comment by RichardLindhout** [comment]
Guys, my PR should fix it without too much changes.

You can also still make other handlers to e.g. buttons inside the modal.

![schermafbeelding 2017-07-29 om 21 00 21](https://user-images.githubusercontent.com/6492229/28747519-1159866a-74a1-11e7-85d2-c975a4d4a26d.png)

**Comment by mmazzarolo** [comment]
Hi @RichardLindhout , thank you for the PR, I'll paste here what I already wrote in the PR thread:

> I took a close look at it and it seems that the idea of the touchable wrapper + the custom pointerEvents still won't work if you tap on the side of the modal content, am I right?

**Comment by RichardLindhout** [comment]
If you press the black it will close. The modal itself will not receive touch events but the children will.
See https://facebook.github.io/react-native/docs/view.html#pointerevents

So I can still have other handlers for my 'OK' button or select text inside the modal. (or date pickers for instance will still work)

![schermafbeelding 2017-07-29 om 21 31 37](https://user-images.githubusercontent.com/6492229/28747698-59b91250-74a5-11e7-8d52-20b2daa1cef1.png)

**Comment by mmazzarolo** [comment]
@RichardLindhout I'm so happy to say that I was wrong, I fired up the emulator and it seems to be working perfectly so far!  
It's super weird, because I tried an identical solution to the one you proposed when this issue was opened and it didn't work.  
I guess this might be related to an update of React-Native, because I guess even @zhantx did try a similar solution in the past.  

Thank you @RichardLindhout  for sending the PR, anyone else willing to test it?  
I'll gladly merge it once someone else other than me and @RichardLindhout give it a try and can confirm that it works and doesn't break anything. 

One last thing @RichardLindhout, may I suggest renaming `hideOnBackdrop` to `hideOnBackdropPress`?

**Comment by RichardLindhout** [comment]
@mmazzarolo Thank you, I will rename the variable.
Anyways below is a GIF which I made a few minutes ago to prove that it worked :)


![jul -29-2017 21-47-29](https://user-images.githubusercontent.com/6492229/28747784-ab6ae6d0-74a7-11e7-8129-6bf337b621c6.gif)

**Comment by mmazzarolo** [comment]
@RichardLindhout No worries, I tried it with the example repo and it works indeed.  
I just need a bit of testing from someone else too, because this modal is used in many different ways and I'd like to know if this feature will break anything.  

Also, one last thing, for maintaining backward compatibility I think it would be better making `hideOnBackdropPress` default to `false`, what do you think?

**Comment by RichardLindhout** [comment]
Yes I agree, I also did not tested on Android yet.

**Comment by ifiokjr** [comment]
I've just tested this on Android, and it doesn't quite seem to work. Tapping to the left or right will sometimes close the modal, but above and below have no effect. 

I'll have a look at what's causing the issue later on - hopefully, today if I get time.

**Comment by mmazzarolo** [comment]
@ifiokjr, thank you, I suspect that the modal content being defined as "flex" might be the root cause of the issue.  
I still do not understand why it works on iOS though... Maybe it is something we should report and discuss on the react-native official repo too.  

Also, @ifiokjr, what version of react-native are you using?

**Comment by ifiokjr** [comment]
@mmazzarolo I'm using 0.46.4.

**Comment by dark1991** [comment]
use onPanResponderGrant for check your position tap.
You can use event.nativeEvent.locationY compare with pageY and set visible for modal.

**Comment by bronylexx** [comment]
Tapping outside to close works fine in the example from the repo (`git clone...; react-native run-ios`). However, whenever I try to replicate that behaviour in my own code, it never works. Is there something special in the example code?

**Comment by bronylexx** [comment]
Looks like I was able to solve it by using git repo (`yarn add git-url`) as opposed to npm (`yarn add react-native-modal`).

**Comment by mmazzarolo** [comment]
@dark1991 do you mind providing an example repo/snippet/PR?

**Comment by dark1991** [comment]
@mmazzarolo : Check this link first: https://facebook.github.io/react-native/docs/panresponder.html.
focus on locationX, locationY, PageX and PageY. 

You can use console for log to see position you are tap on model view.
```
onPanResponderGrant: (evt, gestureState) => {
       if(event.nativeEvent.locationY !==event.nativeEvent.pageY){
this.setState({visible:false})
}
      },
```
For more information, check here: https://www.youtube.com/watch?v=HzpuBZK3Ef0

**Comment by mmazzarolo** [comment]
@dark1991, did you already try it with a `flex: 1` view as a child? 
I'm asking this because me and some other users tried playing with it when the thread was stil new and it had some issue (especially on Android).  

I can give it another try though 👍

**Comment by tomasreimers** [comment]
@mmazzarolo, the problem is that when you create a layout-only view (one that only has other content and doesn't need to be explicitly rendered) and then change it to a non-layout-only view, it resets its pointerEvents to 'auto' (the default) on android. The animated.view library changes it to a non-layout-only view because CSS transforms are non-layout-only properties.

Long term fix (and further details) here: https://github.com/facebook/react-native/pull/15529

The short term fix is to add a property to the modal such that it is non-layout-only from the beginning: https://github.com/react-native-community/react-native-modal/pull/57

**Comment by mmazzarolo** [comment]
@tomasreimers that's great! 
Unfortunately I'm not able to give it a test on Android yet (I'm still on vacation), anyone else willing to give it a try? @alexkuc @ifiokjr @RichardLindhout

**Comment by mmazzarolo** [comment]
Released on npm on `3.0.0`, I'll add the release notes this evening.  
Anyone willing to give it a try?

**Comment by mmazzarolo** [comment]
The release notes of `v3.0.0` are [here](https://github.com/react-native-community/react-native-modal/releases/tag/v3.0.0).  
I already submit two other fixes (we're now on `v3.0.2`) and we should be stable now, any other test will be super appreciated. 
Thanks to anyone who contributed on this issue!

**Comment by alexkuc** [comment]
I am going to give it a shot shortly. Just wanted to clarify that I use the setup properly. Previously, I was wrapping inside of Modal with `<TouchableWithoutFeedback>`. With #11 being fixed, does it mean I no longer need to use `<TouchableWithoutFeedback>`?

**Comment by mmazzarolo** [comment]
@alexkuc, yep, just set the visibility of the modal to false in the `onBackdropPress` callback :)

**Comment by Doko-Demo-Doa** [comment]
Yesssssss
Since the issue is solved. I think it can be closed now.

**Comment by mmazzarolo** [comment]
It took so long but we did it!  🎈 

Feel free to open another issue if needed.

**Comment by tomasreimers** [comment]
@mmazzarolo , I mean the bug was *literally* in compiler (or interpreter in this case): the optimizer of React Native's Java's ShadowNode tree. I think it's fair this one took a while to solve lol 😂

Now just to get react-native to accept their fix so we can remove our hacky fix. If you want to jump on and +1 the fix or add context, that would be much appreciated: https://github.com/facebook/react-native/pull/15529

**Comment by hustlerism** [comment]
Hi I'm still having this issue. 

`_hideModal = () => {
      this.setState({ isModalVisible: false })
  }`

Passed a function as prop to a custom component `<ModalBox />`

`onPress={this._hideModal}`

In `<ModalBox />`

`<Modal 
      isVisible={this.props.isModalVisible}      
      onBackdropPress={this.props.onPress}
      >`

It wont close after tapping on the backdrop. But when i use it in  `<Button />` inside the modal, it works.

**_"react-native": "0.44.2",
"react-native-modal": "3.1.1",_**

**Comment by mmazzarolo** [comment]
Are you using Expo by any mean? 
Could you try updating react-native?

**Comment by hustlerism** [comment]
@mmazzarolo 

Nope, i'm not using Expo.

Btw, the problem solved. The react-native-modal package didnt update properly. My bad.

Thanks for the quick response.

**Comment by jbyrneie** [comment]
Hi Guys

I tried the above suggestions but they dont work for me

When I click outside the modal my _hideModal() is not fired.

I am using RN 0.47.2 and react-native-modal 3.0.2

import React, { Component } from 'react'
import {StyleSheet, Text, TouchableOpacity, TouchableWithoutFeedback, View} from 'react-native'
import Modal from 'react-native-modal'

class ConfirmSchedule extends Component {
  constructor(props) {
    super(props);
  }

  _hideModal() {
    alert('hideModal')
  }

  render () {
    return (
      <TouchableWithoutFeedback onPress={() => this._hideModal() }>
      <View style={styles.container}>
          <Modal
            transparent={true}
            style={styles.bottomModal}
            isVisible={this.props.visible} >
            <View style={styles.modalContent}>
              <Text style={styles.info}>Some text</Text>
            </View>
        </Modal>
      </View>
      </TouchableWithoutFeedback>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 22,
    borderRadius: 4,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  bottomModal: {
    margin: 20,
  },
})

module.exports = ConfirmSchedule;

**Comment by nahuelr** [comment]
That works greats for me, only use one layer behind options.
u have to make touchable the content of modal, not the modal per se.

```javascript
                <View>
                    <Modal
                        animationType="slide"
                        transparent={true}
                        visible={this.state.modalVisible}
                        onRequestClose={() => {
                            this.closeModal();
                        }}>
                        <TouchableWithoutFeedback //this touchable close modal
                                onPress={() => {
                                    this.closeModal();
                                }}>
                            <View style={{flex:2,backgroundColor:'#6666669c'}}>//layer behind modal options
                                {this.renderOptionList()}
                            </View>
                        </TouchableWithoutFeedback>
                    </Modal>
                </View>
```

**Comment by jbaek7023** [comment]
Hi guys, 

I just found this issue and tried hard to read all of your comments and suggestions. 
Here is what I've tried
- Adding onBackDropPress(() => {this.props.hideModal()})
- Adding TouchableWithoutFeedback inside and outside of components
- other approaches...

Here is my the screen where I want to show my modal.
```
render() {
return (
<View style={{flex: 1}}>
        <ScrollView>
          // CONTENT HERE
          {this._renderModal()} //rendering modal here
          <FABs onFABsPress={this._showModal} /> // I open Modal when I press the FABs button
        </ScrollView>
      </View>));

_renderModal = () => {
    return (
      <CameraImageSelectModal
        hideModal={this._hideModal}
        isModalVisible={this.state.isModalVisible}
        navigation={this.props.navigation}
      />
    )
  }
```

Here is modal component : CameraImageSelectModal.js 
```
  render() {
    let { isModalVisible } = this.props;
    return (
      <View>
        <Modal
          isVisible={isModalVisible}
          hideOnBackdropPress={false}
          transparent={true}>
          <View style={styles.modalContainer}>
            <View style={styles.modalTitleTextContainer}>
              <Text style={styles.modalTitleText}>Hello World</Text>
            </View>
            <View style={styles.modalContentTextContainer}>
              <Text style={styles.modalContentText}></Text>
            </View>
            <View style={styles.modalButtonContainer}>
              <Button transparent onPress={this._handleCameraPress}>
                <Text style={[styles.modalText, styles.black]}>Camera</Text>
              </Button>
              <Button transparent onPress={this._handleAlbumPress}>
                <Text style={styles.modalText}>Album</Text>
              </Button>
            </View>
          </View>
        </Modal>
      </View>
```

Thanks!!

**Comment by jbaek7023** [comment]
Nevermind. I just updated the react-native-modal to the newer version and it solved my problem. Thanks!! 

(I was using 2.5.0 version lol)

**Comment by alessiocancian** [comment]
For anyone who wants to use Modal from react-native here is the correct implementation:
`
<Modal>
  <TouchableWithoutFeedback onPress={onBackdropPress}>
    <View  style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0}} />
  </TouchableWithoutFeedback>
  <View style={{flex: 1, ...}}>
    Modal Content
  </View>
</Modal>
`
This is actually the react-native-modal's implementation of backdropPress

**Comment by adirzoari** [comment]
@jbaek7023  onBackdropPress works for u?

**Comment by CezarCobuz** [comment]
> @Doko-Demo-Doa according to the source code, haven't implemented yet, there is no close event on backdrop view or you can do sth like this, not so good but should be work.
> 
> ```
> <TouchableWithoutFeedback onPress={() => this.setState({ visible: false })}>
>         <Modal isVisible={this.state.visible}  ...>
>             <TouchableWithoutFeedback onPress={() => {}}>
>                     ... your custom view
>             </TouchableWithoutFeedback
>        </Modal>
> </TouchableWithoutFeedback>
> ```

What if there is scrollView inside?

**Comment by darshan-vineeth** [comment]
> > @Doko-Demo-Doa according to the source code, haven't implemented yet, there is no close event on backdrop view or you can do sth like this, not so good but should be work.
> > ```
> > <TouchableWithoutFeedback onPress={() => this.setState({ visible: false })}>
> >         <Modal isVisible={this.state.visible}  ...>
> >             <TouchableWithoutFeedback onPress={() => {}}>
> >                     ... your custom view
> >             </TouchableWithoutFeedback
> >        </Modal>
> > </TouchableWithoutFeedback>
> > ```
> 
> What if there is scrollView inside?

I think this solution would help you.
https://stackoverflow.com/a/40483972/4994493

**Comment by Einere** [comment]
I implements using @DavidKongDesheng 's solution.

```javascript
export function MyModal(props) {
  const {modalVisible = false, onClose, children, preset = 'nonClose'} = props;

  return preset === 'nonClose' ? (
    <Modal animationType="fade" transparent={true} visible={modalVisible}>
      <View style={containerStyle.centeredView}>
        <View style={containerStyle.modalView}>{children}</View>
      </View>
    </Modal>
  ) : (
    <Modal animationType="fade" transparent={true} visible={modalVisible}>
      <TouchableWithoutFeedback onPress={onClose}> // when trigger click modal outside
        <View style={containerStyle.centeredView}>
          <TouchableWithoutFeedback onPress={() => {}}> // prevent trigger onClose when click modal inside
            <View style={containerStyle.modalView}>{children}</View>
          </TouchableWithoutFeedback>
        </View>
      </TouchableWithoutFeedback>
    </Modal>
  );
}
```

**Comment by junaid5546** [comment]
THIS WILL WORK 100%

<Modal
        animationType="fade"
        transparent={true}
        visible={visible}
        onRequestClose={() => {
          Alert.alert("Modal has been closed.");
        }}
      >
        // MODAL WHOLE VIEW


      ---------------------------
      |                                           |
      |       __________________       |
      |       |   //DATA             |      |
      |       |   Nam  JUNAID |      |
      |       |_________________|      |                               
      |                                           | 
      |                                           |
      |___________________________|                                                                                

        <TouchableOpacity
        onPress={() => closeModel()}
          style={{
            height: windowHeight,
            width: windowWidth,
            justifyContent: "center",
            alignItems: "center",
          }}
        >
    // DATA THAT WILL SHOW IN MODAL 
<View
            style={{
              height: windowHeight / 1.5,
              backgroundColor: "pink",
              borderRadius: 10,
              width: windowWidth / 1.1,
            }}
          >  DATA GOES HERE IN THE CENTER
          </View>

</TouchableOpacity>
</Modal>

By clicking anywhere on an empty space modal will dismiss.

**Comment by ChiragALogicalloop** [comment]
> @Doko-Demo-Doa according to the source code, haven't implemented yet, there is no close event on backdrop view or you can do sth like this, not so good but should be work.
> 
> ```
> <TouchableWithoutFeedback onPress={() => this.setState({ visible: false })}>
>         <Modal isVisible={this.state.visible}  ...>
>             <TouchableWithoutFeedback onPress={() => {}}>
>                     ... your custom view
>             </TouchableWithoutFeedback
>        </Modal>
> </TouchableWithoutFeedback>
> ```

It's working.

**Comment by mateoLorenzo1** [comment]
Hi! I've tried most of the aproaches above and any of them seemed to solve the main issue. The last ones works but are half incomplete and difficult to understand, so I leave you here an updated easy to read component that solves the issue.

The code 👇👇👇



```javascript

export const ModalScreen = () => {
  const [isVisible, setIsVisible] = useState(false);

  const showModal = () => {
    setIsVisible(true);
  };

  const hideModal = () => {
    setIsVisible(false);
  };

  return (
    <View style={styles.screenContainer}>
      <Button title="Open Modal" onPress={showModal} />

      <Modal visible={isVisible} transparent>
        <Pressable onPress={hideModal} style={styles.modalContainer}>
          <TouchableWithoutFeedback>
            <View style={styles.modalContent}>
              <Text>Modal Title</Text>
              <Button title="Close Modal" onPress={hideModal} />
            </View>
          </TouchableWithoutFeedback>
        </Pressable>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```

**Comment by pbaker0804** [comment]
> Hi! I've tried most of the aproaches above and any of them seemed to solve the main issue. The last ones works but are half incomplete and difficult to understand, so I leave you here an updated easy to read component that solves the issue.
> 

Works great!  Thanks!
