### ISSUE TITLE
How to avoid keyboard for bottom half modal

### ISSUE THREAD

**Issue by rpereira** [react-native-community/react-native-modal#32]
Let's say we have a bottom half modal with some `TextInput`. How can we avoid the keyboard? I've tried [KeyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview.html) and it did nothing.

CC @mmazzarolo.

Thanks.

**Comment by mmazzarolo** [comment]
Hey @rpereira , it seems that [adding a margin might help](https://github.com/react-native-community/react-native-modal/issues/25), could you test and confirm it?

**Comment by rpereira** [comment]
Hi @mmazzarolo. I've seen that issue and the margin didn't do the trick.

I had to modify the source using a `KeyboardAvoidingView`.

```javascript
      <Modal
        transparent={true}
        animationType={'none'}
        visible={this.state.isVisible}
        onRequestClose={this._closeOnBack}
        {...otherProps}
      >
        <View
          ref={ref => (this.backdropRef = ref)}
          style={[
            styles.backdrop,
            { backgroundColor: backdropColor, width: deviceWidth, height: deviceHeight },
          ]}
        />
        <KeyboardAvoidingView behavior="padding">
          <View
            ref={ref => (this.contentRef = ref)}
            style={[{ margin: deviceWidth * 0.05 }, styles.content, style]}
            {...otherProps}
          >
            {children}
          </View>
      </KeyboardAvoidingView>
      </Modal>
```

If you guys think it is a clean solution, I can submit a PR.

**Comment by mmazzarolo** [comment]
It would be great!  
Could you also add a prop `avoidKeyboard` (with a default `false`) to enable/disable it?  
Mostly for backward compatibility, but also for cases where you don't wont to achieve this effect at all.

In e.g.: 
```javascript
{avoidKeyboard && <KeyboardAvoidingView behavior={'padding'}>}
```

Thank you! 👍

**Comment by rpereira** [comment]
I'll do that @mmazzarolo. 👍

**Comment by rpereira** [comment]
I'll submit a PR next week.

**Comment by galdanay** [comment]
any update?

**Comment by mmazzarolo** [comment]
Hey @rpereira any update?  
I can edit it by myself if needed, let me know :)

**Comment by rpereira** [comment]
Hey @mmazzarolo, I'll do it during the weekend. Sorry for the long delay.

**Comment by mmazzarolo** [comment]
@rpereira no worries man!

**Comment by sejo2016** [comment]
any update?

**Comment by mmazzarolo** [comment]
@sejo2016, I just merged a PR made by @G3z that should address the issue, do you mind giving it a try (by running `yarn add git+https://github.com/mmazzarolo/react-native-modal-datetime-picker.git`)?  

Thanks!

**Comment by hironarita** [comment]
@mmazzarolo, I just installed the package and setting avoidKeyboard to true doesn't seem to work for me.

**Comment by G3z** [comment]
hi, try this please https://github.com/react-native-community/react-native-modal/pull/65

**Comment by mmazzarolo** [comment]
Landed on [v4.0.0](https://github.com/react-native-community/react-native-modal/releases/tag/v4.0.0), thanks @g3z and @rpereira.

**Comment by brayanL** [comment]
I have any specific solution?

**Comment by fredrivett** [comment]
FWIW for those coming from Google, I solved this by using a nested `KeyboardAvoidingView` inside my Modal (the `avoidKeyboard` mentioned above in v4 didn't work for me).

```
<Modal>
  <KeyboardAvoidingView
    behavior="position"
    enabled
  >
    {myContent}
  </KeyboardAvoidingView>
</Modal>
```

Note: `behaviour="position"`, this didn't work when using `padding` for me.

**Comment by Jalson1982** [comment]
Hello. I just tried @fredrivett  solution but it also do not work. I have modal and in modale some heading, content and complete button on bottom:0. If wrap all in KeyboardAvoidingView , when open modal, button is on text input not on his original position bottom:0. If try to set padding not position it does not work. Any working solution for this?

**Comment by thomasarogers** [comment]
@fredrivett have also tried solution but did not work. Tried setting exact height as well as flex but no luck. 

![image](https://user-images.githubusercontent.com/42372294/55084551-3fae8400-509d-11e9-9d7a-17d19a09dec0.png)

**Comment by alemkhodadadi** [comment]
hi everybody.
i tried setting style={{position: 'absolute', width: 0.9*WIDTH, height: 0.9*HEIGHT}} to modal and it worked!

**Comment by haripermadi** [comment]
any update?

**Comment by knapcio** [comment]
I encountered a similar problem working with https://github.com/jacklein/rn-bottom-drawer
My temporary fix: position drawer contents absolutely when the keyboard is shown.

```
class BottomDrawerWrapper extends Component {
	state = {
		keyboardHeight: 0,
	}

	componentDidMount () {
		this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow);
		this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);
	}

	componentWillUnmount () {
		this.keyboardDidShowListener.remove();
		this.keyboardDidHideListener.remove();
	}

	_keyboardDidShow = e => {
		this.setState({ keyboardHeight: e.endCoordinates.height });
	}

	_keyboardDidHide = () => {
		this.setState({ keyboardHeight: 0 });
	}

	render () {

		const {
			isOpen,
			close,
			component,
		} = this.props;

		const {
			keyboardHeight,
		} = this.state;


		const Component = component;

		return isOpen && (
			<BottomDrawer
				
			>
				<View style={{ 
					backgroundColor: '#fff', 
					// the hack: position absolutely the content if keyboardHeight > 0
					...(keyboardHeight === 0 ? {} : { position: 'absolute', bottom:  keyboardHeight, left: 0, right: 0 }) }}>
					<Component />
				</View>
			</BottomDrawer>
		);
	}
}
export default BottomDrawerWrapper;

**Comment by Hobahung** [comment]
Hey, you can try using "behavior={Platform.OS === "android" ? undefined : "position"}"

<Modal
        ref={modal => (this.modal = modal)}
        propagateSwipe={true}
        swipeDirection="down"
        onSwipeComplete={() => this.props.closeModal()}
        style={[styles.modalContainer, { }]}
        isVisible={showCoupon}>
        <KeyboardAvoidingView enabled  behavior={Platform.OS === "android" ? undefined : "position"}>
          <ScrollView scrollEnabled={false} keyboardShouldPersistTaps="handled">
          <View style={[styles.modalContent, { flex: 1 }]}>
            {CONTENT}
          </View>
        </ScrollView>
        </KeyboardAvoidingView>
      </Modal>

For Style: 
modalContainer: {
    padding: 0,
    margin: 0,
    backgroundColor: Color.transparent,
    justifyContent: 'flex-end'
  },
  modalContent: {
    alignItems: 'center',
    backgroundColor: Color.white,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingBottom: 30
  }

This work for me!

**Comment by Hobahung** [comment]
Hey, you can try using "behavior={Platform.OS === "android" ? undefined : "position"}"

```
<Modal
        isVisible={showCoupon}>
        <KeyboardAvoidingView enabled  behavior={Platform.OS === "android" ? undefined : "position"}>
          <ScrollView scrollEnabled={false} keyboardShouldPersistTaps="handled">
          <View style={[styles.modalContent, { flex: 1 }]}>
          </View>
        </ScrollView>
        </KeyboardAvoidingView>
</Modal>
```

For Style: 
```
modalContainer: {
    justifyContent: 'flex-end'
  },
  modalContent: {
  }
```

This work for me!

**Comment by louiCoder** [comment]
> Hey, you can try using "behavior={Platform.OS === "android" ? undefined : "position"}"
> 
> ```
> <Modal
>         isVisible={showCoupon}>
>         <KeyboardAvoidingView enabled  behavior={Platform.OS === "android" ? undefined : "position"}>
>           <ScrollView scrollEnabled={false} keyboardShouldPersistTaps="handled">
>           <View style={[styles.modalContent, { flex: 1 }]}>
>           </View>
>         </ScrollView>
>         </KeyboardAvoidingView>
> </Modal>
> ```
> 
> For Style:
> 
> ```
> modalContainer: {
>     justifyContent: 'flex-end'
>   },
>   modalContent: {
>   }
> ```
> 
> This work for me!

THIS HAS WORKED FOR ME LIKE A CHARM 🤓

**Comment by mxhunt** [comment]
> Hey, you can try using "behavior={Platform.OS === "android" ? undefined : "position"}"
> 
> ```
> <Modal
>         isVisible={showCoupon}>
>         <KeyboardAvoidingView enabled  behavior={Platform.OS === "android" ? undefined : "position"}>
>           <ScrollView scrollEnabled={false} keyboardShouldPersistTaps="handled">
>           <View style={[styles.modalContent, { flex: 1 }]}>
>           </View>
>         </ScrollView>
>         </KeyboardAvoidingView>
> </Modal>
> ```
> 
> For Style:
> 
> ```
> modalContainer: {
>     justifyContent: 'flex-end'
>   },
>   modalContent: {
>   }
> ```
> 
> This work for me!

Hey, where do i have to place the "modalContainer" Style. Can´t find it in the Modal code block.

**Comment by VienLeVan** [comment]
> Hey, you can try using "behavior={Platform.OS === "android" ? undefined : "position"}"
> 
> ```
> <Modal
>         isVisible={showCoupon}>
>         <KeyboardAvoidingView enabled  behavior={Platform.OS === "android" ? undefined : "position"}>
>           <ScrollView scrollEnabled={false} keyboardShouldPersistTaps="handled">
>           <View style={[styles.modalContent, { flex: 1 }]}>
>           </View>
>         </ScrollView>
>         </KeyboardAvoidingView>
> </Modal>
> ```
> 
> For Style:
> 
> ```
> modalContainer: {
>     justifyContent: 'flex-end'
>   },
>   modalContent: {
>   }
> ```
> 
> This work for me!

Thanks you, it worked for me

**Comment by Hobahung** [comment]
> > Hey, you can try using "behavior={Platform.OS === "android" ? undefined : "position"}"
> > ```
> > <Modal
> >         isVisible={showCoupon}>
> >         <KeyboardAvoidingView enabled  behavior={Platform.OS === "android" ? undefined : "position"}>
> >           <ScrollView scrollEnabled={false} keyboardShouldPersistTaps="handled">
> >           <View style={[styles.modalContent, { flex: 1 }]}>
> >           </View>
> >         </ScrollView>
> >         </KeyboardAvoidingView>
> > </Modal>
> > ```
> > 
> > 
> > For Style:
> > ```
> > modalContainer: {
> >     justifyContent: 'flex-end'
> >   },
> >   modalContent: {
> >   }
> > ```
> > 
> > 
> > This work for me!
> 
> Hey, where do i have to place the "modalContainer" Style. Can´t find it in the Modal code block.

Hey, remove this :D

**Comment by TaraSinghDanu** [comment]
None of the above solution worked for me.

**Comment by luan-nvg** [comment]
I have the same problem in June :(

**Comment by LB-Digital** [comment]
By random experimentation, I have just found that setting a negative `extraHeight` value on the KeyboardAwareScrollView seems to solve my issue, sits the text input just above the keyboard.

```
<Modal>
    <View style={ styles.contentContainer }>
        <KeyboardAwareScrollView
            extraHeight={-100}
            keyboardOpeningTime={10}
            style={ styles.content }
        >
            <TextInput/>

        </KeyboardAwareScrollView>
    </View>
</Modal>
```

**Comment by luaninfocast** [comment]
hello lucas, how are you? my problem was a little more complicated, because of a failure to use this feature that hides 70% and this does not take into account the size of the modal that I set, for example: if I apply what the modal modifies 40% of the screen , or the keyboard applies based on screen size, not size of the modal I created

**Comment by luan-nvg** [comment]
hello @LB-Digital , how are you? my problem was a little more complicated, because of a failure to use this feature, after I created the modal I informed that it would occupy 40% of the screen, added a TextInput, and when focusing on it the keyboard was open, however at the open the keyboard he was not taking into account the open mode, but the size of the screen

tip: never use flex and percentage together

**Comment by kckunal2612** [comment]
For me, the above solutions didn't work. So I followed the example given on React Native official documentation.
https://reactnative.dev/docs/keyboardavoidingview.html#example
This is what I did with my Modal (having a TextInput in the bottom half that was getting overlapped with the Keyboard) -

```
 <Modal
      animationType="slide"
      transparent={true}
      visible={props.isVisible}
      onRequestClose={props.onClose}
    >
      <KeyboardAvoidingView
        behavior={isIOS() ? "padding" : "height"}
        style={styles.container}
      >
        <View style={styles.container}>
          <View style={styles.centerSubContainer}>{props.children}</View>
        </View>
      </KeyboardAvoidingView>
    </Modal>
```

And the styles are as below -
```
const styles = StyleSheet.create({
    centerSubContainer: {
      backgroundColor: colors.white.white,
      elevation: 5,
      padding: variables.basicUnit,
      shadowColor: colors.black.black,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    container: {
      alignItems: "center",
      flex: 1,
      justifyContent: "center",
    },
  });
```

**Comment by luan-nvg** [comment]
> Para mim, as soluções acima não funcionaram. Então, segui o exemplo dado na documentação oficial do React Native.
> https://reactnative.dev/docs/keyboardavoidingview.html#example
> Foi o que fiz com o meu Modal (com um TextInput na metade inferior que estava sendo sobreposto ao teclado) -
> 
> ```
>  <Modal
>       animationType="slide"
>       transparent={true}
>       visible={props.isVisible}
>       onRequestClose={props.onClose}
>     >
>       <KeyboardAvoidingView
>         behavior={isIOS() ? "padding" : "height"}
>         style={styles.container}
>       >
>         <View style={styles.container}>
>           <View style={styles.centerSubContainer}>{props.children}</View>
>         </View>
>       </KeyboardAvoidingView>
>     </Modal>
> ```
> 
> E os estilos são os seguintes -
> 
> ```
> const styles = StyleSheet.create({
>     centerSubContainer: {
>       backgroundColor: colors.white.white,
>       elevation: 5,
>       padding: variables.basicUnit,
>       shadowColor: colors.black.black,
>       shadowOffset: {
>         width: 0,
>         height: 2,
>       },
>       shadowOpacity: 0.25,
>       shadowRadius: 3.84,
>     },
>     container: {
>       alignItems: "center",
>       flex: 1,
>       justifyContent: "center",
>     },
>   });
> ```


my problem and you were trying to use flexbox as an alternative, or what is incorrect, to troubleshoot or use a percentage instead of setting the width: 500, I set the width: '50% 'or use Dimensions.get ( 'window'). height / 2 which is exactly half the screen I now have two options for use

**Comment by ebatgerel** [comment]
Any solution for this ? I have the same issue

![image](https://user-images.githubusercontent.com/16677052/89387244-cca72a00-d734-11ea-94d2-b5069659895d.png)

**Comment by ebatgerel** [comment]
It should be looks like:

![image](https://user-images.githubusercontent.com/16677052/89387377-fceec880-d734-11ea-9822-118adf27c2aa.png)

**Comment by luan-nvg** [comment]
> Deve ser parecido com:
> 
> ![imagem](https://user-images.githubusercontent.com/16677052/89387377-fceec880-d734-11ea-9822-118adf27c2aa.png)

    <KeyboardAvoidingView>

**Comment by salimmtp** [comment]
my model contained lots of `TextInput` inside `ScrollView`
As suggested above, I did wrap my model content inside `KeyboardAvoidingView`.

```
<Modal {...Props}>
    <View style={{flex:1}}>
        <KeyboardAvoidingView behavior="padding">
            <ScrollView>
                {content}
            </ScrollView>
        </KeyboardAvoidingView>
    </View>
</Modal>
```

But the problem was when clicking on the Top area `TextInput`, The whole content went above the viewport, And the user was unable to see the `TextInput`. 

Fixed it using the package [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view)

```
import {KeyboardAwareScrollView} from 'react-native-keyboard-aware-scroll-view';

<Modal {...Props}>
    <View style={{flex:1}}>
        <KeyboardAwareScrollView>
             {content}
         </KeyboardAwareScrollView>
    </View>
</Modal>
```

**Comment by siyurichen** [comment]
> It should be looks like:
> 
> ![image](https://user-images.githubusercontent.com/16677052/89387377-fceec880-d734-11ea-9822-118adf27c2aa.png)

you can set like this

<View style={{height: 610, justifyContent: 'flex-end'}}>
   <KeyboardAvoidingView behavior="padding">
.......
   </KeyboardAvoidingView>
</View>

the height 610 is your keyboard height, it works for me

**Comment by sobanarshad85** [comment]
> ```js
> <KeyboardAvoidingView behavior="padding">
> ```

**Comment by MatiSera** [comment]
Hi! I'm still having this issue, the UI pushes up when the keyboard is enabled.

"react-native-modal": "12.0.2",

**Comment by anasalaqeel** [comment]
for me, all solutions don't work, so I ended up putting `style={{ flex: 1 }}` style and `behavior="padding"` and this works like a charm. see the example below:

```
<Modal visible={true} >
          <KeyboardAvoidingView style={{ flex: 1 }} behavior="padding">
                 { your content }
          </KeyboardAvoidingView>
 </Modal>
```

**Comment by abdollahkhan** [comment]
> It should be looks like:
> 
> ![image](https://user-images.githubusercontent.com/16677052/89387377-fceec880-d734-11ea-9822-118adf27c2aa.png)

use KeyboardAvoidingView after Modal Fragment like below:
<Modal visible={true} >
      <KeyboardAvoidingView style={{ flex: 1 }} behavior="padding">
           { your content }
      </KeyboardAvoidingView>
 </Modal>

**Comment by maidul98** [comment]
<Modal>
<KeyboardAvoidingView style={{ flex: 1, justifyContent: 'flex-end'}} behavior="padding">{your content}></KeyboardAvoidingView>
</Modal>

This worked for me

**Comment by NagaSwathiAmbati07** [comment]
I'm facing same issue. tried above solutions but still not fixed.Here is my code

  <Portal theme={{ colors: { backdrop: 'rgba(0,0,0,0.2)' } }}>
          <Modal
            visible={showDialog}
            dismissable={true}
            onDismiss={hidePopModal}
            contentContainerStyle={{
              position: 'absolute',
              bottom: 10,
              width: '100%',
              height: '50%',
              marginBottom: -50
            }}
          >
            <KeyboardAvoidingView
              style={{ flex: 1, justifyContent: 'flex-end' }}
              behavior="padding"
            >
              <View
                style={{
                  height: '85%',
                  backgroundColor: THEME.primary.colors.white,
                  borderTopRightRadius: 30,
                  borderTopLeftRadius: 30
                }}
              >
                <TouchableOpacity
                  style={styles.crossTouch}
                  onPress={() => {
                    hidePopModal();
                  }}
                >
                  <Menu name="menu-outline" size={35} color="#E8EDF7" />
                </TouchableOpacity>
                <Text style={styles.switchTxt} text=" Add Promo Code" />

                <Card.Content
                  style={{
                    width: '95%',
                    paddingHorizontal: 7,
                    justifyContent: 'center',
                    alignSelf: 'center',
                    marginBottom: 30
                  }}
                >
                  <TextInput
                    mode="outlined"
                    // inputLabel="Enter Promo Code"
                    placeholder="Promo Code"
                    placeholderTextColor="#707070"
                    labelStyle={{ color: colors.secondary, marginTop: 5 }}
                    name={'promo'}
                    id="promo"
                    value={code.promo === 'null' ? '' : code.promo}
                    onChangeText={text => {
                      if (text == '') {
                        text = 'null';
                        setPromoId(undefined);
                      }
                      onChange(text, 'promo');
                    }}
                    onBlur={() => onBlur('promo')}
                  />
                  {promoId &&
                    (promoId == 'null' ? (
                      <HelperText
                        style={{
                          color: colors.red,
                          paddingHorizontal: 0,
                          fontSize: 13,
                          fontFamily: 'DMSans-Bold',
                          fontWeight: '400'
                        }}
                      >
                        Code is not Valid
                      </HelperText>
                    ) : (
                      <HelperText
                        style={{
                          color: 'green',
                          paddingHorizontal: 0,
                          fontSize: 13,
                          fontFamily: 'DMSans-Bold',
                          fontWeight: '400'
                        }}
                      >
                        Code Applied Successfully
                      </HelperText>
                    ))}
                </Card.Content>
                <Button
                  label="Apply"
                  disabled={code.promo == 'null'}
                  style={
                    code.promo != 'null'
                      ? [
                          { backgroundColor: colors.secondary },
                          styles.couponButton
                        ]
                      : [
                          { backgroundColor: colors.accent },
                          styles.couponButton
                        ]
                  }
                  labelStyle={
                    code.promo != 'null'
                      ? [
                          {
                            color: colors.primary,
                            fontSize: 16,
                            fontFamily: 'DMSans-Regular',
                            fontWeight: '400'
                            // marginBottom: 20
                          },
                          styles.btnText
                        ]
                      : [
                          {
                            color: colors.accentgray,
                            // marginBottom: 20,
                            fontSize: 16,
                            fontFamily: 'DMSans-Regular',
                            fontWeight: '400'
                          },
                          styles.btnText
                        ]
                  }
                  onPress={() => {
                    Keyboard.dismiss();
                    onPromoCode();
                    // hidePopModal();
                    // setPromoVisible(false)
                  }}
                />
              </View>
            </KeyboardAvoidingView>
          </Modal>
        </Portal>

**Comment by AhmedAbuelenin** [comment]
This what worked for me.

```
<Modal style={{flex: 1}>
     <KeyboardAvoidingView
            style={{flex: 1, justifyContent: 'flex-end'}} 
            behavior={Platform.OS === 'android' ? 'padding' : 'position'}>
                <Container style={{height: '80%'}}> // use your desired height here
                  // whatever your content here
               </Container>
    </KeyboardAvoidingView>
</Modal>
```

Hope this work for you too.

**Comment by Rutheniceye92** [comment]
In my case it worked when I removed `autoFocus` from `TextInput`.

**Comment by mmsmadi** [comment]
anyone facing problem with keyboard not avoiding content inside modal try setting 
`statusBarTranslucent={false}` 

I dont know why is that but this worked for me.

**Comment by thisisadithk** [comment]
I am using react-native paper's Modal and tried all the above fixes but still not working. Can anyone please help ? Code is as below..

` const renderRenameModal = (state, setState) => {
    return (
      <Portal>
        <Modal
          visible={visible}
          onDismiss={hideModal}
          contentContainerStyle={[
            styles.shareGroupModalContainer,
            { height: screenHeight * 0.48 },
          ]}
          style={{
            justifyContent: "flex-end",
            marginBottom: 0,
          }}
        >
          <KeyboardAvoidingView style={{ flex: 1 }} behavior="padding">
            <View
              style={{
                flex: 0.4,
                flexDirection: "row",
                justifyContent: "center",
                paddingTop: 10,
              }}
            >
              <RNImg
                source={{ uri: props.route.params.albumData.image_url }}
                style={{
                  flex: 1,
                  resizeMode: "contain",
                  height: null,
                  width: null,
                }}
              />
            </View>
            <View
              style={{
                flex: 0.3,
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <Text>Rename Album</Text>
              <TextInput
                // label={"Enter your Album name"}
                value={state}
                onChangeText={(text) => setState(text)}
                placeholderTextColor={Colors.greyText}
                autoCapitalize={"none"}
                autoComplete={"off"}
                autoCorrect={false}
                mode={"flat"}
                autoFocus
                outlineColor={Colors.White}
                underlineColor={Colors.greyLine}
                activeUnderlineColor={Colors.tertiaryColor}
                activeOutlineColor={Colors.tertiaryColor}
                style={[
                  {
                    backgroundColor: Colors.White,
                    fontSize: moderateScale(17),
                    height: screenHeight * 0.07,
                    width: screenWidth * 0.7,
                  },
                ]}
                textColor={Colors.primaryColor}
              />
            </View>
            <View
              style={{
                flex: 0.2,
                flexDirection: "row",
                justifyContent: "center",
              }}
            >
              <View
                style={{
                  flex: 0.65,
                  flexDirection: "row",
                  justifyContent: "space-around",
                  marginTop: 18,
                }}
              >
                <TouchableOpacity
                  onPress={() => setVisible(false)}
                  style={styles.RenameButtons}
                >
                  <Text style={{ color: Colors.tertiaryColor }}>Cancel</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={handleRenameAlbum}
                  style={[
                    styles.RenameButtons,
                    { backgroundColor: Colors.tertiaryColor },
                  ]}
                >
                  {doneLoading ? (
                    <ActivityIndicator
                      animating={doneLoading}
                      color={Colors.White}
                      size={25}
                    />
                  ) : (
                    <Text style={{ color: Colors.White }}>Done</Text>
                  )}
                </TouchableOpacity>
              </View>
            </View>
          </KeyboardAvoidingView>
        </Modal>
      </Portal>
    );
  };
  
  const styles = StyleSheet.create({
  shareGroupModalContainer: {
    backgroundColor: "white",
    padding: 18,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
![Simulator Screen Shot - iPhone 13 - 2023-01-25 at 12 15 22](https://user-images.githubusercontent.com/95686047/214498006-c3cb12bd-135c-43a4-b91c-40e7bdbc9b98.png)

  `
![Simulator Screen Shot - iPhone 13 - 2023-01-25 at 12 14 54](https://user-images.githubusercontent.com/95686047/214497925-2f08daff-e439-494a-92f7-5f5730230316.png)

**Comment by mmsmadi** [comment]
> react-native paper's Modal

if it doesnt includes any prop for keyboard avoiding try using keyboard listeners.

**Comment by krmao** [comment]
None of above works for me, I don't want all the half modal move up on keyboard up, only need keyboad bellow the input,
so got some code, both worked for android and ios, ios need ScrollView scrollEnabled for behavior padding
```typesript
render() {
    const { contentNode, enableLoading } = this.props;
    const { visible } = this.state;
    const avoidKeyboardAll = this.props.avoidKeyboardAll ?? true;
    return (
      <Modal
        isVisible={visible}
        onBackButtonPress={() => this.dismiss()}
        deviceHeight={SCREEN_HEIGHT}
        deviceWidth={WINDOW_WIDTH}
        statusBarTranslucent={true}
        avoidKeyboard={false}
        coverScreen={true}
        style={styles.modalRoot}
        //region backdrop
        hasBackdrop={true}
        backdropColor={'#000000'}
        backdropOpacity={0.4}
        backdropTransitionInTiming={0}
        backdropTransitionOutTiming={0}
        onBackdropPress={() => this.dismiss()}
        //endregion
        onModalHide={() => this.props.onModalHide?.()}
        focusable={true}
        hideModalContentWhileAnimating={false}
        animationInTiming={270}
        animationIn={'slideInUp'}
        animationOutTiming={270}
        animationOut={'slideOutDown'}
      >
        {/*https://github.com/magicismight/react-native-root-toast/issues/64#issuecomment-631852017*/}
        <RootSiblingParent inactive={!visible}>
          <KeyboardAvoidingView
            behavior={'padding'}
            style={[styles.modalContainer, { width: displayUtil.WINDOW_WIDTH }]}
          >
            <ScrollView
              scrollEnabled={!displayUtil.IS_ANDROID}
              keyboardShouldPersistTaps="handled"
              nestedScrollEnabled={true}
              persistentScrollbar={false}
              showsHorizontalScrollIndicator={false}
              showsVerticalScrollIndicator={false}
              overScrollMode={'never'}
              fadingEdgeLength={0}
              bounces={false}
              bouncesZoom={false}
              alwaysBounceVertical={false}
              alwaysBounceHorizontal={false}
              contentContainerStyle={{
                justifyContent: 'flex-end',
                flex: avoidKeyboardAll ? 1 : 0,
                height: displayUtil.WINDOW_HEIGHT_WITH_STATUS_BAR,
              }}
            >
              <TouchableWithoutFeedback onPress={() => this.dismiss()}>
                <View style={{ flex: 1, width: '100%' }} />
              </TouchableWithoutFeedback>
              {contentNode ?? <View style={[styles.modalContent]} />}
              {!!enableLoading && <this.LoadingComponent />}
            </ScrollView>
          </KeyboardAvoidingView>
        </RootSiblingParent>
      </Modal>
    );
  }
```

**Comment by mmsmadi** [comment]
I guess behavior={'padding'} is causing the issue

try behavior={platform.OS==="ios"?'padding':null}

**Comment by yogeshjugwan** [comment]
<KeyboardAwareScrollView enableOnAndroid={true} style={{height:"100%"}}
            enableAutoAutomaticScroll={(Platform.OS === 'ios')} extraHeight={130} extraScrollHeight={130}>
                <View>
                  <FormInput />
                 </View>
      </KeyboardAwareScrollView>

**Comment by lavisar-luckytech** [comment]
In the newest version have the **avoidKeyboard** props, I have tried and it fix my issues

![Screenshot 2024-07-26 at 17 50 01](https://github.com/user-attachments/assets/98d04aa8-1227-4084-a462-fd3c0eafb5a9)

**Comment by lavisar** [comment]
In the newest version have the **avoidKeyboard** props, I have tried and it fix my issues

![Screenshot 2024-07-26 at 17 50 01](https://github.com/user-attachments/assets/98d04aa8-1227-4084-a462-fd3c0eafb5a9)
